### PR TITLE
Call for Content: 2020/06

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by domenkozar** [comment]
- [Github actions powered by Nix Shell & Cachix](https://gvolpe.github.io/blog/github-actions-nix-cachix-dhall/)

**Comment by ryantm** [comment]
```
- [NixOS: How it works and how to install it!](https://www.youtube.com/watch?v=oPymb2-IXbg)
  
  An excellent video on installing NixOS.
```

**Comment by domenkozar** [comment]
https://www.tweag.io/blog/2020-06-18-software-heritage/

**Comment by Mic92** [comment]
```markdown
- [RFC 70](https://github.com/NixOS/rfcs/pull/70): Merge nixos-hardware into nixpkgs
```

**Comment by domenkozar** [comment]
- [Mach-nix: Create python environments quick and easy](https://github.com/DavHau/mach-nix)

**Comment by jonringer** [comment]
Edit, meant to clear my comment, not close the PR oops:

```
- [NixOS 20.09 Release Manager](https://discourse.nixos.org/t/nixos-20-09-release-manager/7800/6) has been selected.
```

**Comment by domenkozar** [comment]
- [netboot.nix: 15 second netboot iterations](https://github.com/grahamc/netboot.nix/)

- [Windows-on-NixOS, part 2: Make it go fast!](https://nixos.mayflower.consulting/blog/2020/06/17/windows-vm-performance/)

- [ZuriHac: overhaul of haskell.nix tutorials](https://input-output-hk.github.io/haskell.nix/)

- [Nix error messages proposal: phase 2, PR 1 merged!](https://opencollective.com/nix-errors-enhancement/updates/nix-error-enhancement-phase-2-pr-1-merged)

  Nearly every C++ file in the repo was touched! This will be the biggest PR, by far, for this project. Getting this in is a major feat!
  Next up, I'm looking forward to finishing out this phase with showing the lines of code for errors, and supporting show-trace in the new format. I expect that PR to be much easier, both to make the changes and to review them.

**Comment by marsam** [comment]
```
- [homelab using Nix and NixOS](https://thewagner.net/blog/2020/05/31/homelab/)
- [PureScript on Nix without dependency codegen](https://qiita.com/kimagure/items/9e75483c1263d85169e5)
```

**Comment by Mic92** [comment]
```
- [Nix & libSystem](https://daiderd.com/2020/06/25/nix-and-libsystem.html)

  How nixpkgs links against macOS's system libraries.
```

**Comment by ryantm** [comment]
```
- [home-manager template](https://github.com/ryantm/home-manager-template)

  Quickly get started using home-manager in a more reproducible way.
```

**Comment by mt-caret** [comment]
```
- [Encypted Btrfs Root with Opt-in State on NixOS](https://mt-caret.github.io/blog/posts/2020-06-29-optin-state.html)
```

**Comment by etu** [comment]
```
 - [NixOS ❄: tmpfs as root](https://elis.nu/blog/2020/05/nixos-tmpfs-as-root/) & [NixOS ❄: tmpfs as home](https://elis.nu/blog/2020/06/nixos-tmpfs-as-home/)

Tutorial with step by step instructions for installing NixOS on tmpfs. Also an introduction to how to have a usable `/home` on tmpfs.
```

**Comment by domenkozar** [comment]
Thanks all!

**Pull request merged**
