### PR TITLE
Call for Content: 2019/07

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by Ekleog** [comment]
A bit in the outskirts of the nix world, but it might be of interest. Information given by @timokau at https://github.com/NixOS/nix/issues/859#issuecomment-480490112 :
```
- [The IPFS team made package managers their top priority for 2019](https://github.com/ipfs/roadmap#2019-priorities)

There might be progress on its [nix integration](https://github.com/ipfs/package-managers/blob/master/package-managers/nix.md).
```

Thank *you* <3

**Comment by timokau** [comment]
May be a good idea to also add a link to their file on nix: https://github.com/ipfs/package-managers/blob/master/package-managers/nix.md

**Comment by Ekleog** [comment]
Edited my message to make it easier to copy-paste, thanks! :)

**Comment by domenkozar** [comment]
- [Statically link Haskell executables and optionally create Docker images or Debian packages](https://alexandre.peyroux.io/posts/2019-04-06-nix-and-haskell.html)

- [Concourse CI on NixOS](https://memo.barrucadu.co.uk/concourseci-nixos.html)

**Comment by domenkozar** [comment]
Moving to next week :)

**Comment by domenkozar** [comment]
https://discourse.nixos.org/t/nixos-19-03-release/2652

**Comment by domenkozar** [comment]
http://davedellacosta.com/posts/2019-03-29-why-nixos-is-hard-and-how-to-fix.html

**Comment by domenkozar** [comment]
- [Hercules CI sprint #1 development update](https://blog.hercules-ci.com/sprints,/hercules-ci/2019/04/16/sprint-1-report/)

- https://ilikewhenitworks.gitlab.io/posts/2019-04-14-mixing-channels-in-nixos.html

**Pull request merged**
