### PR TITLE
Call for Content: 2020/10

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by Mic92** [comment]
- [NixOS cloud images](https://nixos.cloud/)

  Additional NixOS install images for Amazon (aarch64, x86_64), openstack and kexec

**Comment by domenkozar** [comment]
- [autopatchelf - allowing arbitrary binaries to run on NixOS](https://fzakaria.com/2020/12/01/autopatchelf-what-it-can-look-like.html)

- [A content addressable store for Nix with Théophane Hufschmitt](https://www.compositional.fm/content-addressable-nix-1)

- [Mobile NixOS: November 2020 round-up](https://mobile.nixos.org/news/2020-12-01-november-2020-round-up.html)

- [Deploying with GitHub Actions and more Nix](https://thewagner.net/blog/2020/12/06/deploying-with-github-actions-and-more-nix/)

**Comment by Mic92** [comment]
```
- [tex2nix](https://github.com/Mic92/tex2nix)
  Generate small texlive environments for your document
```

**Comment by domenkozar** [comment]
https://justinas.org/nixos-in-the-cloud-step-by-step-part-1

**Comment by Mic92** [comment]
```
- [nix-ld](https://github.com/Mic92/nix-ld)
  Run unpatched dynamic binaries on NixOS.
```

**Comment by domenkozar** [comment]
https://scrive.github.io/nix-workshop/

**Pull request merged**
