### PR TITLE
Call for Content: 2019/10

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by domenkozar** [comment]
http://nixery.appspot.com/

**Comment by 7c6f434c** [comment]
HTTPS version of the link works too.

**Comment by tazjin** [comment]
It should actually auto-redirect to HTTPS by setting an HSTS header 🤔 

Anyways, feel free to include Nixery (and maybe also [this Twitter thread](https://twitter.com/tazjin/status/1129817483064557570)) but please add a disclaimer saying that this is an experiment only :)

**Comment by domenkozar** [comment]
- [Using NixOS as an stateless workstation](https://euandre.org/2019/06/02/stateless-os.html)

**Comment by etu** [comment]
- [nix-mode.el](https://github.com/NixOS/nix-mode) now have support for the indentation function `smie-indent-line` in [NixOS/nix-mode#79](https://github.com/NixOS/nix-mode/pull/79) & [NixOS/nix-mode#80](https://github.com/NixOS/nix-mode/pull/80). Thanks to @j-piecuch and @matthewbauer for the work and testing.

**Comment by gbpdt** [comment]
- [PDT Partners is looking for an experienced engineer](https://jobs.pdtpartners.com/?gh_jid=1473543)

  For our Software Infrastructure team, which is responsible for our build, packaging, CI and deployment 
  tooling.  We’re using Nix to package our complex C++ and Python stack, and as part of our wider 
  development environment for our fast-moving trading and research applications.

**Comment by domenkozar** [comment]
- [Complete overkill or exactly right? Deploying a static site using nix ](http://mpickering.github.io/posts/2019-06-24-overkill-or-not.html)

**Comment by gilligan** [comment]
[Introducing nixpkgs-tungsten: The most convenient way to working with Tungsten Fabric](https://dev.cloudwatt.com/en/blog/introducing-nixpkgs-tungsten.html)

[Tungsten Fabric](https://tungsten.io) is the open-source offering of [Contrail](https://www.juniper.net/us/en/products-services/sdn/contrail/) by Juniper Networks - a powerful SDN solution used by many big names in the IT industry. The [nixpkgs-tungsten](https://github.com/cloudwatt/nixpkgs-tungsten) project provides tools and workflows that make it much easier to work with, and on Tungsten Fabric itself. [Cloudwatt](https://www.cloudwatt.com/) is using it in production very successfully.

**Comment by domenkozar** [comment]
Thanks all :)

**Pull request merged**
