### PR TITLE
Call for Content: 2019/03

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch or comment below. Thank you <3

### CODE REVIEW

**Comment by Lassulus** [comment]
- [netboot.xyz](https://github.com/antonym/netboot.xyz/issues/37)

NixOS is finally bootable via netboot.xyz

**Comment by domenkozar** [comment]
- [Nix SRE position in Helsinki, Finland](https://relex.recruiterbox.com/jobs/fk0jx41/)

**Comment by domenkozar** [comment]
https://github.com/nmattia/niv

**Comment by makefu** [comment]
https://github.com/nmattia/niv - Easy dependency management for Nix projects

**Comment by domenkozar** [comment]
https://www.softinio.com/post/moving-from-homebrew-to-nix-package-manager/

**Comment by makefu** [comment]
* [The case of the supersized shebang]( https://lwn.net/SubscriberLink/779997/11de2bdc8dbc0d69/ ) - regression in the linux kernel all together with backporting the issue into all stable kernels

**Comment by Lassulus** [comment]
- [Diving into NixOS](https://rycwo.xyz/2018/07/29/nixos-series-dual-boot)

**Comment by domenkozar** [comment]
- [Deploying k8s apps with kubenix](https://zimbatm.com/deploying-k8s-apps-with-kubenix/)

**Comment by fpletz** [comment]
* [The status.im project starts moving to Nix](https://discuss.status.im/t/the-road-to-nix-a-functional-package-manager-to-rule-them-all/1049)

**Comment by vcunat** [comment]
@makefu: while the LWN article certainly is an interesting read, isn't that link meant to be subscriber-only ATM?

**Comment by 7c6f434c** [comment]
@vcunat this link is readable without subscription right now.

Asfar as I understand as a on-subscriber, LWN allows subscribers to share a world-readable link to subscriber-only articles.

**Comment by vcunat** [comment]
Yes, it is reachable, as I'm not a subscriber :-)  which is also why I don't know what are the link-sharing rules and why I posted my comment more as a question.  EDIT: I mean, sharing with a few individuals is one thing, posting world-wide-readable links is something else...

**Comment by vcunat** [comment]
Hmm, I suppose it's OK ([link](https://lwn.net/op/FAQ.lwn#slinks)):

> Where is it appropriate to post a subscriber link?
> Almost anywhere. Private mail, messages to project mailing lists, and blog entries are all appropriate. As long as people do not use subscriber links as a way to defeat our attempts to gain subscribers, we are happy to see them shared.

**Pull request merged**
