### PR TITLE
add status blog post

### PR DESCRIPTION
**Pull request by sixhobbits**
Add status blog post

### CODE REVIEW

**Comment by Ericson2314** [comment]
BTW in your blog post:

> Nix is a tool which uses a subset of [Haskel](https://www.haskel.com/) programming language to define the entire tree of software dependencies necessary to manage an entire Linux operating system: NixOS.

1. Haske**ll** has two "l"s
2. The website is actually https://www.haskell.org/
3. Neither the Nix language or Haskell is a subset of the other, though they both use some sort of lazy evaluation.

I'm not mad----that sentence gave me a good chuckle---but thought you might want to know before the post gets publicized.

**Comment by sixhobbits** [comment]
Nice catch :) I'm not involved with Status / this blog post at all. I just found it and thought it would fit well here, but I'll try get their attention somehow.

**Comment by sixhobbits** [comment]
opened https://github.com/status-im/status.im/issues/527

**Comment by domenkozar** [comment]
Thanks!

**Pull request merged**
