### PR TITLE
Call for Content: 2019/05

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by mogorman** [comment]
- [Nixos 19.03 Koi Artwork](https://www.redbubble.com/people/mogorman/works/37459559-nixos-19-03-koi)
  Artwork for the upcoming release. [updated merchant report for the release](https://discourse.nixos.org/t/nixos-merchandise-report/303/6)

**Comment by danbst** [comment]
- [Why you should never ever use NixOS](https://dev-ops-notes.com/nixos/why-you-should-never-ever-use-nixos/)

  Rant from someone, who is forced to maintain NixOS in AWS. Some are silly (like kernel upgrade), but lot's of good points

**Comment by domenkozar** [comment]
Not enough content, moving to next week.

**Comment by domenkozar** [comment]
https://blog.hercules-ci.com/cachix/nix/2019/03/07/announcing-private-cachix/

**Comment by o1lo01ol1o** [comment]
- [CI / CD Job](https://discourse.nixos.org/t/job-request-post/2324)
  Recent IP development company is looking for someone with strong Nix skills to move the nix build infrastructure for our currently in-development mobile / web application to a CI/CD solution on AWS.

**Comment by domenkozar** [comment]
- [DevOps engineer at groq](https://www.linkedin.com/jobs/view/1154264442/)

**Comment by domenkozar** [comment]
Thanks all :)

**Pull request merged**
