### PR TITLE
Call for Content: 2020/04

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by matthewbauer** [comment]
- [Announcing Nixiosk](http://matthewbauer.us/blog/nixiosk.html)

  Declarative Kiosk systems built with NixOS.

**Comment by davidak** [comment]
- [Announcing Marketing Team](https://discourse.nixos.org/t/marketing-team-can-we-present-nix-nixos-better/6249)

  The marketing team was founded and had their first meeting. They already improved the website (see [Learn page](https://nixos.org/learn.html)). If you want to join, you find the details in the announcement post. Let's improve the presentation of Nix/NixOS!

**Comment by domenkozar** [comment]
https://sgt.hootr.club/molten-matter/dotnet-on-nix/

**Comment by Mic92** [comment]
- [nix-update](https://github.com/Mic92/nix-update/)
  A tool for updating nix packages semi-automatically

**Comment by davidak** [comment]
Also mention that:

- [nixpkgs-update](https://github.com/ryantm/nixpkgs-update)

  automatically runs now on nix-community infrastructure

https://github.com/ryantm/nixpkgs-update/issues/13#issuecomment-605716161

**Comment by Mic92** [comment]
> Also mention that:
> 
>     * [nixpkgs-update](https://github.com/ryantm/nixpkgs-update)
>       automatically runs now on nix-community infrastructure
> 
> 
> [ryantm/nixpkgs-update#13 (comment)](https://github.com/ryantm/nixpkgs-update/issues/13#issuecomment-605716161)

I will add a FAQ to my project how nix-update is different from nixpkgs-update.

**Comment by bhipple** [comment]
It looks like you've only just recently started work `nix-update` in the last couple weeks.  Is there any real reason to write a second tool that does basically the same thing as `nixpkgs-update`?  Notably:

1. `nixpkgs-update` *does* fetch release information from both github releases and pypi.  
2. `nixpkgs-update` also updates both Rust and Go packages.
3. `nixpkgs-update` can be run stand-alone to update/build/test a single package interactively, or even send a PR for that one package in isolation, see this build/PR, which I ran as myself from a local feature branch checkout of `nixpkgs-update`: https://github.com/NixOS/nixpkgs/pull/82465
4. `nixpkgs-update` does not have to send pull requests on its updates (see the `--dry-run`, which will just update/build/test/report locally).

It being in Haskell is a bit of a barrier to entry compared to Python, to be sure, but we're trying to improve the test suite, dry runs, logging, and interactive output story in particular to make it easier to integrate new rewrite rules for the updater.  It'd be nice for us to combine resources and work together rather than splitting our efforts to re-implement the same logic.  I've found @ryantm to be extremely active and helpful in accepting/integrating improvements.

**Comment by ryantm** [comment]
Thanks @bhipple. I was thinking the same thing. At this point, the main hurdle I see to most people using nixpkgs-update interactively is the installation story. The issues with that are tracked here https://github.com/ryantm/nixpkgs-update/issues/137

**Comment by ryantm** [comment]
Currently, the nixpkgs-update PyPi and GitHub fetching only happens in batch mode, not interactively. Seems like a good feature to add though.

**Comment by Mic92** [comment]
> It being in Haskell is a bit of a barrier to entry compared to Python, to be sure, but we're trying to improve the test suite, dry runs, logging, and interactive output story in particular to make it easier to integrate new rewrite rules for the updater. It'd be nice for us to combine resources and work together rather than splitting our efforts to re-implement the same logic. I've found @ryantm to be extremely active and helpful in accepting/integrating improvements.

Yes. ryantm's version did not really provided the workflow needed for end-users. My implementation is not really a loss for your project. I tried several times to learn Haskell but I don't understand its errors messages and documentation, so I would not contribute to your implementation much.

**Comment by marsam** [comment]
```
- [Create and Publish a Website with Hakyll, HAProxy and NixOS](https://www.thomasbach.dev/posts/2020-04-03-website-init.html)

- [Declarative, Decentralised, and Secure communication via Matrix, Jitsi, & NixOS](https://kaushikc.org/posts/matrix-jitsi-nixos.html)
```

**Comment by domenkozar** [comment]
- https://blog.niteo.co/project-isolation-beyond-requirements-txt/

- https://grahamc.com/blog/erase-your-darlings

- https://serokell.io/blog/hiring-sre

- https://splintah.gitlab.io/posts/2020-04-13-emacs-local-nix-environment.html

- https://blog.ysndr.de/posts/internals/2020-04-10-built-with-nix/

- https://blog.patchgirl.io/2020/02/29/building-a-web-app-with-fp-intro.html

**Comment by Mic92** [comment]
- [20.03 was released](https://discourse.nixos.org/t/nixos-20-03-release)

**Comment by domenkozar** [comment]
https://discourse.nixos.org/t/contract-work-for-the-next-generation-internet/6840

**Pull request merged**
