### PR TITLE
Call for Content: 2019/13

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by domenkozar** [comment]
- [ociTools in NixOS](https://spacekookie.de/blog/ocitools-in-nixos/)

  Katharina explains about her recently merged Open Container Initiative support in NixOS

**Comment by marsam** [comment]
- [nix-emacs-ci](https://github.com/purcell/nix-emacs-ci)
  Emacs installations for continuous integration

- [Setting up a Custom Nix Channel](https://savanni.luminescent-dreams.com/2019/09/13/nix-channel/)

- [How to put your /nix directory on a separate device](https://cs-syd.eu/posts/2019-09-14-nix-on-seperate-device)

- [Strange Loop 2019:  "Functional DevOps in a Dysfunctional World" by Vaibhav Sagar](https://www.youtube.com/watch?v=baTsrF9_zi0)

- [NixOS binary cache improvements](https://www.notion.so/Cache-Work-db97de6ab19b4d7ab9f4a60cb4cdaaf0)

- [Mobile NixOS Development Log (2)](https://samuel.dionne-riel.com/blog/2019/09/25/mobile-nixos-development-log-2.html)

- [All Systems Go!: "Purely Functional Package Management" by Franz Pletz](https://www.youtube.com/watch?v=OhBsUPRHIKI)

**Comment by domenkozar** [comment]
- [Post-mortem on recent Cachix downtime](https://blog.hercules-ci.com/2019/09/30/recent-cachix-downtime/)

**Comment by domenkozar** [comment]
- [Cachix & Nix Install actions for GitHub](https://discourse.nixos.org/t/cachix-nix-install-actions-for-github/4242)

**Comment by domenkozar** [comment]
- [Hercules CI Agent 0.5.0 with Terraform support and simpler configuration](https://blog.hercules-ci.com/2019/10/07/agent-0.5.0-more-terraform-less-configuration/)

**Comment by ryantm** [comment]
```
- [RFC 0052 FCP, Away from static IDs](https://github.com/NixOS/rfcs/pull/52)

The Final Comment Period for RFC 0052 has started and, barring any blocking issues, will be merged after 2019-10-18. Your opinions, comments, and approvals are welcome!
```

**Comment by nlewo** [comment]
- [Tekton Pipelines - the Nix way](https://lewo.abesis.fr/posts/2019-09-30-tekton-pipelines-the-nix-way.html)

 Building Docker images from Nix expressions in a Kubernetes cluster with the Tekton Pipeline project.

**Pull request merged**
