### PR TITLE
Mention the big stdenv refactors in flight

### PR DESCRIPTION
**Pull request by Ericson2314**
CC @globin

### CODE REVIEW

**Comment by Mic92** [comment]
cc @volth who automated refactorings like that in the past.

**Comment by Mic92** [comment]
I would argue that it would be easier to port bash/coreutils to windows than porting nixpkgs :)

**Comment by volth** [comment]
> I would argue that it would be easier to port bash/coreutils to windows than porting nixpkgs :)

I started with this though but gave up quickly.
Now Guix's  approach (write imperative logic on lisp then execute directly or auto-translate to bash) looks promising.

**Comment by Ericson2314** [comment]
@volth I actually agree bash must eventually go; I think these are actually good first steps because the saner and smaller the bash is the easier it is to rewrite. The more people see that the bash can be refactored and complexity reduced, the more open to further, more ambitious changes they will be.

**Pull request merged**
