### PR TITLE
Add 2018/05

### PR DESCRIPTION
**Pull request by domenkozar**
Leave a comment if you'd like to get something in :)

### CODE REVIEW

**Comment by ryantm** [comment]
Snack (a new Haskell build tool that uses nix) is in alpha, requesting feedback

https://www.reddit.com/r/haskell/comments/91f5r7/snack_incremental_nix_builds_for_haskell/
https://github.com/nmattia/snack

**Comment by domenkozar** [comment]
https://matthewbauer.us/blog/beginners-guide-to-cross.html

**Comment by symphorien** [comment]
https://github.com/symphorien/nix-du (shameless self-promotion :° )
Goal: Visualise which gc-roots to delete to free some space in your nix store 
What's new since last time: never announced on this newsletter, only on the mailing-list, it gained optimised store support since that announcement.

**Comment by TravisWhitaker** [comment]
[Anduril Industries](https://www.anduril.com/careers/) uses Nix and is hiring functional programmers to work in a variety of fields (computer vision, parameter estimation, detection and tracking, machine learning) and languages (Haskell, Rust, C++, and Nix of course!).

**Comment by samueldr** [comment]
As long as we're shamelessly self-promoting:

 * https://github.com/samueldr/nix-top

`nix-top` is a tool which allows high-level monitoring of builds locally happening. It will report with a processes listing, shown independently for each output.

(Do tell if the summary is too short)

**Comment by garbas** [comment]
https://discourse.nixos.org/t/nixos-18-09-jellyfish-to-be-forked-off-in-a-month/596

**Comment by arianvp** [comment]
Gave a talk in Utrecht about nix. 
It was recorded 
 But hasnt been uploaded yet. However here are the slides https://arianvp.github.io/nixtalk/slides/slides.html

**Comment by grahamc** [comment]
> I would like to specifically call out a massive thank-you to vcunat and samueldr for being 18.09's release managers, an important and central role in each release. Thank you Vladimír and Samuel!

**Pull request merged**
