### PR TITLE
07 Weekly News Issue

### PR DESCRIPTION
**Pull request by garbas**
**Date:** 2017-04-28
**Editor:** ??? (Looking for a volunteer)

# Help, Help, Help

A substantial part of the effort of publishing the "weekly" news is collecting the news in the first place. If you see anything cool, want to share a job, meetup or presentation **add a comment**.

It's super helpful! Thank you!

### CODE REVIEW

**Comment by adelbertc** [comment]
PR for adding some of my intro blog posts on Nix: https://github.com/NixOS/nixos-weekly/pull/36

**Comment by garbas** [comment]
@adelbertc you might also consider adding your blog post to the planet.nixos.org by editing and sending PR on this file -> https://github.com/NixOS/nixos-org-configurations/blob/master/nixos-org/planet-feeds.nix

**Comment by adelbertc** [comment]
@garbas Oh cool - thanks! Once I figure out/implement tagging for my blog I'll be sure to do that.

**Comment by garbas** [comment]
Hello nixers,

finding the package that provides a certain file in nixpkgs can be hard. That is why I've written a tool to make the process easier, which I thought would be helpful for other people as well: https://github.com/bennofs/nix-index

There was also announcement on the mailing list.

**Comment by Profpatsch** [comment]
Nix at Linux Infotag Augsburg:
https://twitter.com/Profpatsch/status/856403598942580736

lit

**Comment by garbas** [comment]
@Profpatsch care to write a blog post what happened at Linux Infotag?

**Comment by Profpatsch** [comment]
Darn, what a great way to finally start up my blog. Yes.

**Comment by garbas** [comment]
Create a blog with styx
https://styx-static.github.io/styx-theme-hyde/posts/2016-09-19-blog-tutorial.html

**Comment by Profpatsch** [comment]
@garbas http://profpatsch.de/blog/posts/nixos-on-lit-2017.html

Preliminary blog post. Link is fix, wasn’t able to finish my blog backbone. But the content should be final. :)

**Comment by garbas** [comment]
Lets get this out!!!!

**Pull request merged**
