### PR TITLE
Call for Content: 2019/11

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by adisbladis** [comment]
The Nixcon 2019 CfP is open https://discourse.nixos.org/t/the-nixcon-2019-cfp-is-now-open/3318 https://cfp.nixcon.org/nixcon2019/cfp

**Comment by nh2** [comment]
I added some entries in https://github.com/NixOS/nixos-weekly/commit/acef64dfe7ad6aebf6685bdd9f9fff03bf8a5c03. Didn't notice that the Github Edit button would immediately make the commit here -- I hope that is OK, otherwise I can fix things if you tell me what I should do.

**Comment by domenkozar** [comment]
I prefer people editing here, I go through before I publish anyway :)

- [Cachix 0.2.1 released](https://github.com/cachix/cachix/blob/master/cachix/CHANGELOG.md#021---2019-07-05)

  Upgrade via the usual:  $ nix-env -iA cachix -f https://cachix.org/api/v1/install  
  Most notable improvement is default compression has been lowered to increase 
  bandwidth throughput and it's overridable via `--compression-level`.

**Comment by domenkozar** [comment]
- [Hercules CI #5 update requiredSystemFeatures, Cachix and Darwin support](https://blog.hercules-ci.com/sprints,/hercules-ci/2019/07/09/development-update-5-cachix-darwin/)
  
  Preview access for the CI is expanding to all subscribers as we've reached feature parity for the public launch.

**Comment by adisbladis** [comment]
The NixCon 2019 ticket sale have been announced: https://discourse.nixos.org/t/nixcon-2019-ticket-presale/3434

**Comment by domenkozar** [comment]
- [Functional DevOps in a Dysfunctional World](https://vaibhavsagar.com/blog/2019/07/04/functional-devops/index.html)

**Comment by globin** [comment]
Blog post on NixOS tests: https://nixos.mayflower.consulting/blog/2019/07/11/leveraging-nixos-tests-in-your-project/

**Comment by ryantrinkle** [comment]
Obsidian Systems is hiring a Nix engineer: https://www.reddit.com/r/NixOS/comments/cf8ni3/job_offer_obsidian_systems_is_hiring_a_nix/

**Comment by yorickvP** [comment]
New nixfmt release: https://discourse.nixos.org/t/nixfmt-beta-release/3545, please try it out on your code and give us feedback!

**Comment by domenkozar** [comment]
https://discourse.nixos.org/t/nixery-serve-container-images-straight-from-nix/3579

**Comment by domenkozar** [comment]
https://ian.pw/posts/2019-07-19-nix-nixos-first-impressions.html

**Pull request merged**
