### PR TITLE
05 weekly news

### PR DESCRIPTION
**Pull request by teh**
Note that I left out 'Past Meetups' because we
already have 'Presentations'.

@johbo - template for next time, and PR to collect news.

### CODE REVIEW

**Comment by teh** [comment]
Deterministic python: https://github.com/NixOS/nixpkgs/issues/22570

**Comment by teh** [comment]
Found some random project actually using nix as its package manger: 
http://monte.readthedocs.io/en/latest/packaging.html

**Comment by 7c6f434c** [comment]
>Found some random project actually using nix as its package manger: 
>http://monte.readthedocs.io/en/latest/packaging.html

Well, one of the Monte developers has been contributing to NixPkgs for
a year… Also, not completely random, I think they stress principle of 
least authority in the language and consider Nix to be about stressing
the same POLA in packaging.

**Comment by garbas** [comment]
@teh @johbo is anybody owning this one?

**Comment by peterhoeg** [comment]
Singapore Nix Group: https://www.meetup.com/Singapore-NixOS-Nix-User-Group/

**Comment by Profpatsch** [comment]
`17.03` release party with the release manager in Munich https://www.meetup.com/Munich-NixOS-Meetup/events/238567023/

**Comment by garbas** [comment]
Let's also call that people add their blogs (nixos tag if possible) to this list https://github.com/NixOS/nixos-org-configurations/blob/master/nixos-org/planet-feeds.nix by sending a PR

Then blogs are readable here: http://planet.nixos.org

**Comment by teh** [comment]
https://typing-nix.regnat.ovh/ typing nix progress

**Comment by johbo** [comment]
@garbas I cannot contribute much at the moment, got totally knocked out by a cold :(

**Comment by svanderburg** [comment]
I released Disnix 0.7 almost two weeks ago: https://nixos.org/disnix

**Comment by globin** [comment]
The successful build of https://hydra.nixos.org/build/51054560#tabs-summary should mark the 17.03 release.

**Comment by teh** [comment]
Added some content. I don't have a huge amount of time ATM so I'll leave it to @garbas to decide whether to release now or wait for someone else to fill in more details.

**Comment by garbas** [comment]
@teh thank you! it looks great, I'm going to add the events/meetup and release it on (my) Monday morning.

**Comment by garbas** [comment]
just started on this in case you think i forgot about it :)

**Comment by garbas** [comment]
released!

@teh awesome work!
@johbo  I hope it is nothing serious and you will be back soon :)

**Pull request merged**
