### PR TITLE
Call for content: 2018/06

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```
- Example news item title `with link`_

  (optional) News item description

.. _`with link`: http://example.com
```

either as a comment or PR against `master` branch. Thank you <3

### CODE REVIEW

**Comment by ryantm** [comment]
https://grahamc.com/blog/an-epyc-nixos-build-farm

**Comment by ryantm** [comment]
http://blog.shealevy.com/2018/08/05/understanding-nix's-string-context/

**Comment by thoughtpolice** [comment]
Basically everything in https://github.com/NixOS/nixpkgs/pull/38698 -- I'l try to post a summary soon.

**Comment by domenkozar** [comment]
RFC https://github.com/NixOS/nixpkgs/pull/44196

**Comment by domenkozar** [comment]
ETA lang nix packages https://github.com/eta-lang/eta-nix/tree/etaPackages

**Comment by grahamc** [comment]
https://grahamc.com/blog/an-epyc-nixos-build-farm
> Graham explores and benchmarks an AMD EPYC build server against a differently incredible build server, finding the EPYC's builds are much faster across the board.

**Comment by Ekleog** [comment]
RFC https://github.com/NixOS/nixpkgs/pull/44439

**Comment by svanderburg** [comment]
Two blog posts:

How to deploy Mendix applications with Nix/NixOS: http://sandervanderburg.blogspot.com/2018/08/automating-mendix-application.html

An elaborate blog post that composes the stdenv.mkDerivation {} abstraction function from scratch by using a layered approach: http://sandervanderburg.blogspot.com/2018/07/layered-build-function-abstractions-for.html

**Comment by grahamc** [comment]
An OfBorg update! https://www.patreon.com/posts/timeouts-nix-ci-20643198 build time-outs, push-button deploys, monitoring transparency, and more!

**Comment by domenkozar** [comment]
Moving content to next week.

**Comment by timokau** [comment]
RFC 30: https://github.com/NixOS/rfcs/pull/30

A proposal for a new review workflow based on a set of pull-request states (`needs:review`, `needs:work`). It is intended to help reviewers and contributors get PRs merged quicker and reduce likelihood of PRs getting lost. It also greatly increases the value of non-commiter reviews.

**Comment by Profpatsch** [comment]
`libnix-haskell` released: https://hackage.haskell.org/package/libnix-0.2.0.1

`libnix` provides a nicely typed wrapper around the `nix` command line (for parsing, instantiating and realizing). It also provides wrappers for the `nix-prefetch-url` and `nix-prefetch-git`.

**Comment by domenkozar** [comment]
Thank you all :) Next week: https://github.com/NixOS/nixos-weekly/pull/62

**Comment by timokau** [comment]
Thank you!

**Pull request merged**
