### PR TITLE
Call for Content: 2018/09

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```rst
- Example news item title `with link`_

  News item description in one or two sentences.

.. _`with link`: http://example.com
```

preferably as a PR against `master` branch or a comment below. Thank you <3

### CODE REVIEW

**Comment by grahamc** [comment]
- Help make the Nix ecosystem's docs better! https://docbook.rocks
    
    A lot of people meet DocBook for the first time when they're contributing to the documentation of older, well established open source projects like NixOS. Now there is https://docbook.rocks/ to help you get past the initial hurdle of "what do I do now?" I hope this helps!

**Comment by zimbatm** [comment]
The NixCon 2018 program is now live!
https://twitter.com/nixcon2018/status/1038822631288590338
https://nixcon2018.org/#program

**Comment by domenkozar** [comment]
Going to skip this week again due to low volume of news :)

**Comment by domenkozar** [comment]
Nix 2.1 in https://hub.docker.com/r/nixos/nix/tags/

**Comment by ryantm** [comment]
http://sandervanderburg.blogspot.com/2018/09/creating-nix-build-function.html

**Comment by ryantm** [comment]
http://mpickering.github.io/posts/2018-09-19-nix-artefacts.html

**Comment by domenkozar** [comment]
https://github.com/shajra/example-nix

**Comment by LnL7** [comment]
Nix 2.1 is compatible with macOS 10.14 Mojave, make sure to update _before_ upgrading.

**Comment by domenkozar** [comment]
https://docs.travis-ci.com/user/languages/nix/#default-nix-version

**Comment by globin** [comment]
Building customised images: https://nixos.mayflower.consulting/blog/2018/09/11/custom-images/

**Comment by domenkozar** [comment]
Ah that reminds me I should write a blog post how to create self-installing nixos images: https://github.com/snabblab/snabblab-nixos/blob/master/make-iso.nix

**Comment by domenkozar** [comment]
Thanks all!

**Pull request merged**
