### PR TITLE
11: add Fastly

### PR DESCRIPTION
**Pull request by vcunat**
I hope IPv6 gets fixed soon and won't be worth mentioning...

### CODE REVIEW

**Comment by vcunat** [comment]
I'm not sure if someone involved wants to provide more details around the move, but those can be added later.

**Comment by Mic92** [comment]
But the cache already supports ipv6 before, no? The problem is nixos.org itself.

```console
$ host nixos.org
nixos.org has address 54.217.220.47
nixos.org mail is handled by 20 mx01.udag.de.
nixos.org mail is handled by 10 mx00.udag.de.
$ host cache.nixos.org
cache.nixos.org is an alias for dualstack.v2.shared.global.fastly.net.
dualstack.v2.shared.global.fastly.net has address 151.101.18.217
dualstack.v2.shared.global.fastly.net has IPv6 address 2a04:4e42:4::729
```

**Comment by Mic92** [comment]
Would be great if nixos.org itself could be covered by fastly. Also I don't know what kind of effort this involves.

**Comment by vcunat** [comment]
I hit a short time when `cache.nixos.org` did not have AAAA.

**Comment by vcunat** [comment]
Perhaps we should cross-ref: https://discourse.nixos.org/t/the-nixos-cache-is-now-hosted-by-fastly/1061

@Mic92: there's still a slight DNS regression wrt. IPv6: https://discourse.nixos.org/t/the-nix-cache-is-now-much-faster-for-users-outside-of-north-america-and-europe/496/11

**Comment by domenkozar** [comment]
Yeah let's ref discourse so that discussion can happen.

**Comment by domenkozar** [comment]
Thank you!

**Pull request merged**
