### PR TITLE
Call for Content: 2018/15

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch or comment below. Thank you <3

### CODE REVIEW

**Comment by domenkozar** [comment]
https://events.ccc.de/congress/2018/wiki/index.php/Assembly:NixOS

Also not enough content for this week. Happy xmas!

**Comment by mrVanDalo** [comment]
- [nix-instantiate introduction](https://tech.ingolf-wagner.de/nixos/nix-instantiate/)

  A polite introduction to use nix-instantiate and the NixOS module system to render JSON.

**Comment by mrVanDalo** [comment]
- [TerraNix](https://github.com/mrVanDalo/terranix)

  Terraform is awesome, it would be much more awesome with a NixOS  module system.

**Comment by domenkozar** [comment]
https://lists.debian.org/debian-devel/2019/01/msg00013.html

**Comment by domenkozar** [comment]
https://blog.hercules-ci.com/elm/2019/01/03/elm2nix-0.1/

**Comment by danbst** [comment]
[nix-env replacement for imperative package management, but with declarative core](https://discourse.nixos.org/t/declarative-package-management-for-normal-users/1823/3)

**Comment by grahamc** [comment]
- [nix-mode.el](https://github.com/nixos/nix-mode)'s alternate indentation function `nix-indent-line` has received some very needed indentation improvements in [NixOS/nix-mode#61](https://github.com/NixOS/nix-mode/pull/61), and automated tests and Travis-CI support in [NixOS/nix-mode#63](https://github.com/NixOS/nix-mode/pull/63) thanks to @etu and @matthewbauer.

**Comment by makefu** [comment]
- [Beginners Guide for setting up NixOS on the RaspberryPi 3+]( https://github.com/zupo/nix ) based on the new aarch64 SD-Image built by hydra

**Comment by domenkozar** [comment]
https://nmattia.com/posts/2019-01-15-easy-peasy-nix-versions.html

**Comment by Mic92** [comment]
@grahamc can we get a new release of nix-mode.el?

**Comment by etu** [comment]
@matthewbauer Should we prepare a new release of nix-mode? I could do it but you have done more with nix-mode over the years. I could prepare a 1.4.0 if you approve of it.

cc @Mic92

**Pull request merged**
