### PR TITLE
Call for Content: 2018/12

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```rst
- Example news item title `with link`_

  News item description in one or two sentences.

.. _`with link`: http://example.com
```

preferably as a PR against `master` branch or a comment below. Thank you <3

### CODE REVIEW

**Comment by domenkozar** [comment]
Everyone is working on great news for next week! :)

**Comment by Profpatsch** [comment]
What do you think about changing the newsletter to a bi-weekly format then?

**Comment by ryantm** [comment]
I like the way @domenkozar is doing it now. I bet it's easier for him to remember that every week he has to do something on the weekly: either postpone it or publish it.

**Comment by domenkozar** [comment]
Exactly, currently I'm trying to build a habit to do it every week and improving the process tiny bit each week. I'm confident long term more people will start contributing and the pace will go up. This is the first week that's really quiet :)

**Comment by Profpatsch** [comment]
Awesome, 100% with you.

**Comment by globin** [comment]
The NixOps resources.machines attrset:
https://nixos.mayflower.consulting/blog/2018/10/26/nixops-machine-configs/

**Comment by domenkozar** [comment]
Shouldn't that be added upstream? https://github.com/NixOS/nixops/pull/998

**Comment by ryantm** [comment]
https://discourse.nixos.org/t/ann-eris-a-simple-binary-cache-server/1265

**Comment by ryantm** [comment]
NixCon 2018 talks are live at https://www.youtube.com/channel/UCjqkNrQ8F3OhKSCfCgagWLg/videos

**Comment by ryantm** [comment]
https://discourse.nixos.org/t/news-on-the-security-team/1280

**Comment by domenkozar** [comment]
https://github.com/domenkozar/hnix-lsp

**Comment by lo1tuma** [comment]
> https://github.com/domenkozar/hnix-lsp

There is also https://gitlab.com/jD91mZM2/nix-lsp

**Comment by globin** [comment]
> Shouldn't that be added upstream? [NixOS/nixops#998](https://github.com/NixOS/nixops/pull/998)

I will, haven't found time, yet.

**Comment by tazjin** [comment]
[nixdoc](https://github.com/tazjin/nixdoc) to generate documentation for Nix library functions, NixOS/nixpkgs#49275 for the first generated documentation files and NixOS/nixpkgs#49383 for updated doc strings. Rendered example [available here](https://storage.googleapis.com/files.tazj.in/nixdoc/manual.html#sec-functions-library-debug).

**Comment by zimbatm** [comment]
[ANN] Deployment Working Group: https://discourse.nixos.org/t/nix-deployment-working-group/1299

**Comment by disassembler** [comment]
Nix At Home Slides: https://util.samleathers.com/presentations/nix-at-home.html

Although I may move that around some in the near future, so it might be better to copy it and the css file: (style.css)

**Comment by fadenb** [comment]
Wiki lightning talk slides: https://fadenb.github.io/NixCon2018-nixos.html

**Comment by ryantm** [comment]
http://sandervanderburg.blogspot.com/2018/10/auto-patching-prebuilt-binary-software.html

**Comment by Mic92** [comment]
This looks pretty similar to the `autoPatchelfHook` that we have in nixpkgs for a while.

**Comment by garbas** [comment]
Slides from my talk: https://slides.com/garbas/nixcon-2018-london

At the hackaton I was working on getting a docker images with nix installed, built with nix. The work is still in progress, but getting close: https://github.com/garbas/nix-docker-nix

**Comment by MaxGabriel** [comment]
Someone on the /r/nix subreddit suggested that I post our job opening here:

```
- Job: `Engineer at Mercury`_

  Mercury is hiring a generalist engineer in SF. Mercury uses Nix for development, Hydra for CI, and runs on NixOS on AWS.

.. _`Engineer at Mercury`: https://mercury.co/jobs/generalist_engineer.md

```

I'm unfamiliar with this usage of markdown, tell me if I need to edit this!

**Comment by domenkozar** [comment]
That was me :)

Also: https://github.com/justinwoo/psc-package2nix

**Comment by MaxGabriel** [comment]
Oh, thanks :)

**Comment by Profpatsch** [comment]
`filterSourceGitignore`: Automatic `filterSource` by parsing `.gitignore` files from within nix.
https://github.com/Profpatsch/nixperiments/blob/master/filterSourceGitignore.nix

**Comment by domenkozar** [comment]
@Profpatsch would be good to know how it compares to https://github.com/siers/nix-gitignore

**Comment by Profpatsch** [comment]
> would be good to know how it compares to https://github.com/siers/nix-gitignore

From a quick skimming of the source code, nix-gitignore tries to convert the `fnmatch(3)` strings in a `.gitignore` file to perl regexes valid in nix’s `match`. I first considered that as well, but refrained from doing that becaused I don’t know how correct it can be.
My function opts for translation to nix boolean predicates instead and implements a subset of the gitignore logic as nix functions, aborting for unsupported parts.

**Comment by infinisil** [comment]
https://reddit.com/r/NixOS/comments/9w5j3k/new_stable_version_of_simple_nixos_mailserver_v220/

**Comment by domenkozar** [comment]
@garbas @fadenb @disassembler thanks for slides, but I'd rather see you email them to zimbatm@zimbatm.com so that they are attached to the videos that will be posted :) Thanks again!

**Comment by domenkozar** [comment]
Thanks for bearing with me. I've converted posts to markdown, I think that should be simpler for everyone to contribute. Will send the post out tomorrow morning.

**Comment by asymmetric** [comment]
Does @shlevy’s talk about `require.nix` have some content we can link to?

**Comment by domenkozar** [comment]
Thank you all :)

@asymmetric happy to include any posts like that for next week :)

**Pull request merged**
