### PR TITLE
Call for Content: 2021/05

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by cole-h** [comment]
```markdown
- [terraform-provider-hydra](https://determinate.systems/posts/terraform-provider-hydra/)

  A Terraform provider for declaratively managing Hydra projects and jobsets, Determinate Systems' first open source release.
```

**Comment by siraben** [comment]
```markdown
- [stdenv.lib has been removed from Nixpkgs](https://github.com/NixOS/nixpkgs/pull/125494)
```

**Comment by domenkozar** [comment]
- [Unbreakable Builds On Container Schedulers Without Containers](https://blog.tjll.net/container-scheduling-without-containers/)
- [Cross compilation tutorial](https://nix.dev/tutorials/cross-compilation)
- https://blog.replit.com/nix_dynamic_version
- https://grahamc.com/blog/nixos-on-framework

**Comment by Mic92** [comment]
```markdown
- [Container assignment](https://github.com/ls1-sys-prog-course/task8-container)

  University lecture + assignment + tutorial on how to build a shell for the nix build sandbox with automated tests suite
```

**Comment by ghuntley** [comment]
```
- Gitpod [has shipped a template](https://twitter.com/gitpod/status/1412207422165241858), configured for Nix that gives you pre-built, ephemeral reproducible development environments in the cloud.
```

**Comment by Mic92** [comment]
> ```
> - Gitpod [has shipped a template](https://twitter.com/gitpod/status/1412207422165241858), configured for Nix that gives you pre-built, ephemeral reproducible development environments in the cloud.
> ```

Looks like the tweet no longer exists.

**Comment by domenkozar** [comment]
> > ```
> > - Gitpod [has shipped a template](https://twitter.com/gitpod/status/1412207422165241858), configured for Nix that gives you pre-built, ephemeral reproducible development environments in the cloud.
> > ```
> 
> Looks like the tweet no longer exists.

It does for me?

**Comment by domenkozar** [comment]
https://christine.website/blog/paranoid-nixos-2021-07-18

https://mobile.nixos.org/news/2021-08-03-july-2021-round-up.html

https://gvolpe.com/blog/nixos-binary-cache-ci/

https://blog.thomasheartman.com/posts/bevy-getting-started-on-nixos

**Comment by pstn** [comment]
- [Nix Citizen](https://gitea.xndr.de/philipp/nixcitizen)
Experimental attempt (by me) of packaging a demanding and somewhat complex (in terms of wine setup) wine application by dynamically creating a wine prefix from the nix store path of a generated wrapper script.

**Comment by ajs124** [comment]
- [Solving the y2038 Problem with NixOS and XFS](https://blog.helsinki-systems.de/solving-the-y2038-problem-with-nixos-and-xfs/)
Or how to teach your initrd to add features to a filesystem on bootup.

**Comment by Mic92** [comment]
```
- [microvm.nix](https://github.com/astro/microvm.nix) A Nix Flake to build NixOS and run it on one of several KVM-Hypervisors (cloud-hypervisor, qemu, firecracker, kvmtool, crosvm)
```

**Pull request merged**
