### PR TITLE
Call for Content: 2018/13

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- Example news item title [with a link](http://example.com)

  Optional item description

```

preferably as a PR against `master` branch or a comment below. Thank you <3

### CODE REVIEW

**Comment by Mic92** [comment]
- NixOS 19.03 will leverage [multiple cores](https://github.com/NixOS/nixpkgs/pull/50440) automatically by default for builds and Nix 2.2 will have the sandbox [enabled by default](https://github.com/NixOS/nix/commit/4ea4d0b1a39deb0f12a66e10e4809f2d0ddb324e) on Linux

**Comment by nokomprendo** [comment]
Hi,
I wrote this blog post, a few days ago. If you think it's interesting for nixos-weekly...
[Deploy a C++ web app on Heroku using Docker and Nix](https://nokomprendo.frama.io/tuto_fonctionnel/posts/tuto_fonctionnel_30/2018-11-08-README.html)

**Comment by jtojnar** [comment]
- [Meson 0.48 landed in staging again](https://github.com/NixOS/nixpkgs/pull/46020#event-1973394287)

  Hopefully, it will stick this time.

**Comment by teto** [comment]
- Declarative client mail configuration [with a link](https://github.com/rycee/home-manager/pulls?q=is%3Apr+is%3Aclosed+label%3Amail)

 In the latest months, some work went into home-manager to abstract mail configuration and generate configs for a variety of client-side software. Declare your username/password once and generate configs for afew/alot/astroid/mbsync/offlineimap

**Comment by Mic92** [comment]
[Go cross-compilation](https://github.com/NixOS/nixpkgs/pull/50835) landed in staging. This includes support for Cgo and `buildGoPackage`. [Rust cross-compilation](https://github.com/NixOS/nixpkgs/pull/50866) could follow soon.

**Comment by globin** [comment]
RFC on improving RFCs: nixos/rfcs#36

**Comment by domenkozar** [comment]
```markdown
- [Released cachix 0.1.3](https://hackage.haskell.org/package/cachix-0.1.3/changelog)

```

**Comment by kragniz** [comment]
I want to print a load of new stickers for events, ideas for newer and more involved designs are welcome (or even submit some designs of your own!) See: https://discourse.nixos.org/t/nixos-stickers-for-35c3-and-fosdem/1540

**Comment by grahamc** [comment]
- [OfBorg now uses checks](https://discourse.nixos.org/t/ofborg-now-uses-checks/1558) for build status reports, greatly reducing Nixpkgs reviewers' email load.

**Pull request merged**
