### PR TITLE
Call for Content: 2019/02

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch or comment below. Thank you <3

### CODE REVIEW

**Comment by domenkozar** [comment]
- [Dhall - Year in review](http://www.haskellforall.com/2019/01/dhall-year-in-review-2018-2019.html)

**Comment by Mic92** [comment]
- [nixos-generators](https://github.com/nix-community/nixos-generators)
  The nixos-generators project allows to take the same NixOS configuration, and generate outputs for different target formats i.e. ISO, kexec tarballs, qemu's qcow2 format, google cloud images...

**Comment by globin** [comment]
If this edition happens earlier than next thursday, RFCs 13, 17 and 39 are open for shepherd nomination.

**Comment by danbst** [comment]
Code archeology: 15 years ago Nix files had `.fix` extension. Compare original [MPlayer expression](https://github.com/NixOS/nixpkgs/blob/0.4/pkgs/MPlayer/MPlayer.fix), it's [first rewrite](https://github.com/NixOS/nixpkgs/blob/0.4/pkgs-ng/applications/video/MPlayer/default.fix) and [modern view](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/mplayer/default.nix)

**Comment by domenkozar** [comment]
Moving to next week.

**Comment by makefu** [comment]
[hydra-in-a-bag]( https://github.com/samueldr/hydra-in-a-bag ) by @samueldr aims to provide a one-click^W command solution to running a hydra instance **for development purposes**.

**Comment by domenkozar** [comment]
- [NixOS 19.03 feature freeze](https://discourse.nixos.org/t/nixos-19-03-feature-freeze/1950)

**Comment by matthewbauer** [comment]
I have a short writeup on contributing to NixOS/Nixpkgs written on Discourse. The idea is to make it easier for new users to contribute. You can read it here:

https://discourse.nixos.org/t/call-for-proofreaders-and-beta-testers-for-19-03/1980

**Comment by domenkozar** [comment]
https://discourse.nixos.org/t/nixos-foundation-participating-in-eus-next-generation-internet-initiative/2011

**Comment by domenkozar** [comment]
https://r13y.com/

**Comment by Profpatsch** [comment]
https://www.tweag.io/posts/2019-02-06-mapping-open-source.html

> The repositories of distributions such as Debian and Nixpkgs are among the largest collections of open source (and some unfree) software. They are complex systems that connect and organize many interdependent packages. In this blog post we try to shed some light on them from the perspective of Nixpkgs, mostly with visualizations of its complete dependency.



Also: fancy graphs!

nixverse_ego_networks

**Comment by Mic92** [comment]
* [nix](https://ftp-master.debian.org/new/nix_2.2.1-2.html) is now available in debian

**Comment by ryantm** [comment]
https://iohk.io/blog/how-we-use-nix-at-iohk/

**Comment by grahamc** [comment]
Goodness this is a lot! Maybe split all this in to two weeks worth?

**Comment by domenkozar** [comment]
Well it's technically a monthly :) I don't want to be a news blocker so just ship everything :)

**Comment by globin** [comment]
@domenkozar could you include rfc news?

**Comment by domenkozar** [comment]
Next week once we have a curated list :)

**Pull request merged**
