### PR TITLE
Call for Content: 2018/08

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```rst
- Example news item title `with link`_

  News item description in one or two sentences.

.. _`with link`: http://example.com
```

preferably as a PR against `master` branch or a comment below. Thank you <3

### CODE REVIEW

**Comment by teh** [comment]
Nix overlay to program and use a tomu U2F token: https://github.com/teh/tomu-u2f-overlay

**Comment by Mic92** [comment]
you can add your repository to [NUR](https://github.com/nix-community/NUR) so it is easier to use: @teh

**Comment by domenkozar** [comment]
Not enough content, moving to next week.

**Comment by samueldr** [comment]
Oof, this'll be hard to condense in a sentence or two, given that I don't have a "post" summarizing this.

> New installer bootloader: #33686 updates the bootloader, shedding one of the few remaining old logos, while also adding new features. Mainly, HiDPI options under a new sub-menu, allowing modesetting the console to a readable size!

 * https://github.com/NixOS/nixpkgs/pull/33686

**Comment by Mic92** [comment]
> #33686 adds nicer themes and HiDPI support to our bootloader in the installer iso.

**Comment by dezgeg** [comment]
- `RFC 32: Tweak the process of executing phases in the stdenv for better nix-shell UX`_

  A proposal for making it easier to manually run phases of a build inside a nix-shell.

.. _`RFC 32: Tweak the process of executing phases in the stdenv for better nix-shell UX`: https://github.com/NixOS/rfcs/pull/32

(I don't know if I got the formatting right)

**Comment by zimbatm** [comment]
https://github.com/musnix/musnix - Real-time audio in NixOS

**Comment by a-schaefers** [comment]
- Bootstrap a zfs-on-root NixOS installation using only one command with Themelios. `with link`_

Themelios automates the entire installation process of a NixOS zfs-on-root system using any NixOS livedisk with an internet connection and your git repository. Themelios is flexible with many configuration options and allows for unique, per-machine customization.

.. _`with link`: https://github.com/a-schaefers/themelios

**Comment by domenkozar** [comment]
https://discourse.nixos.org/t/nix-2-1-released/875

**Comment by ryantm** [comment]
Zero Hydra Failures for 18.09 https://github.com/NixOS/nixpkgs/issues/45960

**Comment by ryantm** [comment]
19.03 to be called "Koi" https://github.com/NixOS/nixpkgs/commit/e144899b7492d8fdc48c685516347ba7788245a5#diff-09da2f18ff6731224a67af7f0081d111R6

**Comment by domenkozar** [comment]
https://domenkozar.com/2018/09/04/recent-cachix-downtime/

**Pull request merged**
