### PR TITLE
Call for Content: 2019/12

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by tazjin** [comment]
- [One-page Nix expression language overview](https://github.com/tazjin/nix-1p)

**Comment by etu** [comment]
- [Encrypted ZFS mirror with mirrored boot on NixOS](https://elis.nu/blog/2019/08/encrypted-zfs-mirror-with-mirrored-boot-on-nixos/)

Using the `boot.loader.grub.mirroredBoots` module to have redundant boots with an encrypted ZFS mirror.

**Comment by yorickvP** [comment]
- [Serokell is hiring Nix DevOps Engineers](https://www.notion.so/serokell/tl-dr-Serokell-is-hiring-Nix-DevOps-Engineers-9a33609414344f4fa167078a1a0f7896)

**Comment by tazjin** [comment]
- [Yants - Yet Another Nix Type System](https://gist.github.com/tazjin/ad6d48bc2416335acc5da4a197eb9ddc)
  Yants is a small runtime type-checker for Nix that can check primitives (`int`, `string`, etc.) , simple polymorphic types (`option`, `list`, `attrs`), structs/records, enums, functions and more.

  It features pattern matching for enum variants, pretty-printed function types and other niceties! Check out the link for screenshots.

**Comment by globin** [comment]
NixOS RFC Process: https://nixos.mayflower.consulting/review/nixos-rfc-post/blog/2019/08/19/nixos-rfc-process/

**Comment by domenkozar** [comment]
https://vaibhavsagar.com/blog/2019/08/11/ihaskell-nix-docker/

**Comment by domenkozar** [comment]
- https://samuel.dionne-riel.com/blog/2019/08/21/mobile-nixos-the-present-and-future.html

- https://blog.hercules-ci.com/nix/2019/08/22/pre-commit-git-hooks-for-nix/

**Comment by matthewbauer** [comment]
- [All the versions with Nix](http://matthewbauer.us/blog/all-the-versions.html)

**Comment by domenkozar** [comment]
- [Native support for import-from-derivation](https://blog.hercules-ci.com/2019/08/30/native-support-for-import-for-derivation/)

**Pull request merged**
