### PR TITLE
Call for Content: 2019/09

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by akavel** [comment]
https://github.com/jameysharp/autobake

I tried to add it as a PR during the previous CfC, but somehow it seems I didn't finalize the contribution, as I can't see it anywhere :( don't have enough energy to try and write a summary again, sorry :(

**Comment by ryantm** [comment]
https://www.gnu.org/software/guix/blog/2019/gnu-guix-1.0.0-released/

**Comment by makefu** [comment]
[RFC on setup.nix Python development tool](https://discourse.nixos.org/t/rfc-on-setup-nix-python-development-tool/2831) ( [project source]( https://github.com/datakurre/setup.nix ) )

**Comment by fadenb** [comment]
New SNM release, compatible with NixOS 19.03 ( https://www.freelists.org/post/snm/SNM-Version-220,1 )

**Comment by domenkozar** [comment]
- [nixpkgs macOS stdenv updates](https://matthewbauer.us/blog/darwin-stdenv-update.html)

**Comment by domenkozar** [comment]
- [NixOS Takes Action After 1.2GB/s ZFS Encryption Speed Drops To 200MB/s With Linux 5.0+](https://www.phoronix.com/scan.php?page=news_item&px=NixOS-Linux-5.0-ZFS-FPU-Drop)

**Comment by domenkozar** [comment]
- [nixfmt](https://medium.com/@Serokell/an-opinionated-formatter-for-nix-40b4dbb69ddf)

**Comment by domenkozar** [comment]
https://github.com/turboMaCk/nix-elm-tools

**Comment by grahamc** [comment]
- [Groq.com is seeking a DevOps Engineer](https://groq.bamboohr.com/jobs/view.php?id=12) who will be responsible for maintaining and developing services such as build system, monitoring, name resolution, configuration management, and the like. Groq uses formal methods, Haskell, and NixOS to build processors.

**Comment by domenkozar** [comment]
- [Hercules CI sprint #3 report](https://blog.hercules-ci.com/sprints,/hercules-ci/2019/05/14/sprint-3-report/)

- [gitignore for Nix](https://blog.hercules-ci.com/nix/2019/05/15/nix-gitignore/)

**Pull request merged**
