### PR TITLE
Call for Content: 2019/15

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by marsam** [comment]
- [Deploying a fully automated Nix-based static website](https://bradparker.com/content/posts/2019-11-21-deploying-a-fully-automated-nix-based-static-website.html)
- [NYLUG Presents: "Sneaking in Nix - Building Production Containers with Nix" by Graham Christensen
 ](https://www.youtube.com/watch?v=pfIDYQ36X0k)

**Comment by domenkozar** [comment]
- [Lead DevOps Engineer with NixOs, Rust and Cloudflare](https://holo.host/careers/lead-devops-engineer-with-nixos-rust-and-cloudflare/)

**Comment by svanderburg** [comment]
[A Nix-based functional organization for managing processes](https://sandervanderburg.blogspot.com/2019/11/a-nix-based-functional-organization-for.html)

**Comment by globin** [comment]
[Windows-on-NixOS, part 1: Migrating bare-metal to a VM](https://nixos.mayflower.consulting/blog/2019/11/27/windows-vm-storage/)

**Comment by eonpatapon** [comment]
* [Updating NixOS local VMs](http://blog.patapon.info/nixos-local-vm/)

**Comment by jonringer** [comment]
- [Azure-cli v2.0 support](https://github.com/NixOS/nixpkgs/pull/71797)
    The python `az` package, has been added. Replacing the deprecated node `azure` package.

**Comment by asymmetric** [comment]
Wrote a blog post: [What happens when you run nixos-rebuild](https://asymmetric.github.io/2019/12/21/nixos-rebuild/).

**Comment by domenkozar** [comment]
https://blog.niteo.co/reading-nix-expressions/

**Comment by domenkozar** [comment]
https://github.com/jollheef/appvm

**Comment by ryantm** [comment]
```
- [RFC 0046 FCP, Platform Support Tiers](https://github.com/NixOS/rfcs/pull/46)
  The Final Comment Period for RFC 0046 has started with disposition to merge and, barring any blocking issues, will be merged after 2020-01-12. Your opinions, comments, and approvals are welcome!
```

**Comment by domenkozar** [comment]
https://mobile.nixos.org/news/2020-01-08-december-2019-round-up.html

**Comment by domenkozar** [comment]
Thanks everyone :)

**Pull request merged**
