### PR TITLE
Call for Content: 2020/02

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by misuzu** [comment]
```markdown
- [nix-simple-deploy](https://github.com/misuzu/nix-simple-deploy)

  A Rust rewrite of unmaintained [nix-deploy](https://github.com/awakesecurity/nix-deploy). Any feedback appreciated!
```

**Comment by xzfc** [comment]
```
- [cached-nix-shell: Instant startup time for nix-shell](https://github.com/xzfc/cached-nix-shell)
```

**Comment by globin** [comment]
```
 - [structured-attrs](https://nixos.mayflower.consulting/blog/2020/01/20/structured-attrs/)

   An explanation of __structuredAttrs in stdenv and why we enabling it would be desirable. 
```

**Comment by timokau** [comment]
``` 
- [nix-bisect: Bisect Nix Builds](https://discourse.nixos.org/t/nix-bisect-bisect-nix-builds/5584/3)

 A small command-line tool and python library that makes bisecting nix builds much more convenient. It prevents common pitfalls in simple cases and saves a lot of time in more complicated ones.
```

**Comment by marsam** [comment]
```
- [NixOS: For developers](https://myme.no/posts/2020-01-26-nixos-for-development.html)
```

**Comment by fnords** [comment]
```
- [Oslo NixOS MiniCon 2020](https://blog.hackeriet.no/oslo-nixos-minicon-2020/)
```

**Comment by domenkozar** [comment]
```
- [Running NixOS on a consumer NAS](https://www.codedbearder.com/posts/nixos-terramaster-f2-221/)
```

**Comment by domenkozar** [comment]
```
- [How I Work From Anywhere in the World](https://jezenthomas.com/how-i-work-from-anywhere-in-the-world/)
```

**Comment by domenkozar** [comment]
Thanks all :)

**Pull request merged**
