### PR TITLE
04 weekly news

### PR DESCRIPTION
**Pull request by garbas**
## Timeline

Let's release it 2017-03-13.

## Help needed

- [x] looking for a quote
- [x] include all the comments from this PR
- [x] look for news / announcements at twitter for last 2/3 weeks, [here](https://twitter.com/search?f=tweets&vertical=default&q=nixos&src=typd)
- [x] look at interesting threads in the mailing list for last 2/3

Anybody with commit permission to ``nixpkgs`` should also have push permissions for this repo. You can also ping me (@garbas) to do a quick review.

To start blog in "development mode" run ``nix-shell --run "python run.py"`` then visit ``http://127.0.0.1:5500``. When a blog post is edited URL is automatically reloaded.

To build it run ``nix-build``.

If you push to ``master`` branch then Travis deploy the blog to http://weekly.nixos.org/preview.

If you push to ``production`` then Travis will do deployment to http://weekly.nixos.org.

# Write in comments if you want to make sure something will be mentioned in the newsletter.

or better send PR against the master.

Once merged to master preview can be seen here: http://weekly.nixos.org/preview/

### CODE REVIEW

**Comment by grahamc** [comment]
nixpkgs: allow packages to be marked insecure + rewrite of the nixpkgs configuration docs: https://github.com/NixOS/nixpkgs/pull/23130

**Comment by garbas** [comment]
adev: just a little announcement : The Blue Brain Project recruit and is looking for someone with packaging, NixOS / nix packaging knowledges and with a software engineering background. If any of you might be interested : http://emploi.epfl.ch/page-142376-en.html, The job is in Switzerland, Geneva, Swiss salary and Work visa granted for EU citizen if recruited

**Comment by teh** [comment]
Finally have a working `bazel` - https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+bazel+is%3Aclosed

Now we can start building projects like tensorflow from source for reproducibilty etc

**Comment by teh** [comment]
we have systemd 232 with anonymous users etc. `DynamicUser=yes` 

Will allow us to avoid static allocation of IDs for less important services: https://github.com/NixOS/nixpkgs/issues/20186

**Comment by teh** [comment]
https://github.com/NixOS/nixpkgs/pull/23638/files aarch64 support!

**Comment by 7c6f434c** [comment]
Note that aarch64 support comes with a free reminder for each maintainer with all the packages she or he maintains, one email per package!

**Comment by ericsagnes** [comment]
I gave a talk at the [Tokyo Open Source Conference](https://www.ospn.jp/osc2017-spring/) introducing NixOS basics in Japanese. (Not sure of the policy for non-english materials, please ignore if this doesn't fit the guidelines)
Slides are [here](https://github.com/Tokyo-NixOS/presentations) ([source file](https://github.com/Tokyo-NixOS/presentations/blob/master/2017/03-osc/source.markdown)).

And the [next Tokyo NixOS meetup](https://www.meetup.com/ja-JP/Tokyo-NixOS-Meetup/events/238329705/) will be about Hydra on March 24th.

**Comment by garbas** [comment]
HELP!!! I'm already a week late to do this newsletter and I don't see any free time in next 3 days. Would somebody be willing to help me out?

**Comment by teh** [comment]
@garbas what specific items need doing?

**Comment by grahamc** [comment]
Help instructions have been added up here: https://github.com/nixos/nixos-weekly/pull/26#issue-209876601

**Comment by johbo** [comment]
can help out as well

**Comment by johbo** [comment]
we had a presentation about vulnix last weekend: https://chemnitzer.linux-tage.de/2017/de/programm/beitrag/314

not sure if a video is already online though

**Comment by johbo** [comment]
checking the twitter part on my end now

**Comment by teh** [comment]
@garbas can you give me commit access to this repo? Then I can help more in the future.

**Comment by garbas** [comment]
@teh access granted. coordinate with @johbo since he already started. thank you for stepping in!

**Comment by johbo** [comment]
@garbas do you have any policy regarding the job section? I've updated it based on the comments, assumed it does probably not make sense to carry already announced jobs over.

**Comment by johbo** [comment]
Actually I just noticed that there is the concept of "the Editor" for each post, guess that's been what I did sign up for this round 😄 
@teh maybe you could take care of the next one in this role? By shifting it around we could spread the load a bit.

**Comment by garbas** [comment]
@johbo @teh thank you! ``#04`` looks amazing! Merging shortly.

@johbo there is no policy regarding it. I guess having a job offer there for 2-3 times is ok. also 💯 to share the load. with the baby coming any day now and having still to prepare everything I'm not sure i will be able to do much in next month.

**Comment by johbo** [comment]
@garbas wohoo, babies everywhere 👍 

Could it be that the build of the production branch did not succeed or at least the auto deploy did not work out?

**Comment by garbas** [comment]
it looks like something wasn't right with the travis run for production branch, i pushed it manually also i'm sending the emails (using mailchimp).

**Comment by garbas** [comment]
done! newsletter is out

**Pull request merged**
