### PR TITLE
2018/01 weekly newsletter, collecting content

### PR DESCRIPTION
**Pull request by garbas**
### What has been done some far:

- a design has been slightly improved
- a template for future articles has been added. it is a starting point, we can definitely do better.
- selected the quote for 2018/01 newsletter
- wrote some introduction text
- display articles by year

# Please write a comment what you wish to be included in next newsletter!

This newsletter is going to be published on Monday, 2018-01-08, all the comments until end of Sunday, 2018-01-07, will be included.

Thank you and happy 2018 🎆 🎉 🎈 🍰 !

Preview of 2018/01 newsletter is here -> http://weekly.nixos.org/preview/2018/01-phoenixes-burst-into-flame.html
Preview of whole site is here -> http://weekly.nixos.org/preview

### CODE REVIEW

**Comment by domenkozar** [comment]
## Tooling

- https://github.com/domenkozar/elm2nix
- https://github.com/input-output-hk/stack2nix

**Comment by svanderburg** [comment]
* New version of [node2nix](https://www.npmjs.com/package/node2nix) providing initial support for NPM 5.x (that is included with Node.js 8.x)
* New API/tool: [node-hydra-connector](https://github.com/svanderburg/node-hydra-connector) to integrate Node.js applications with the Hydra continuous integration service and a CLI tool that can be used to control a server

**Comment by svanderburg** [comment]
A couple of months old, but I also created [composer2nix](https://github.com/svanderburg/composer2nix) that can be used to generate Nix expressions from [PHP composer](https://getcomposer.org) package specifications

**Comment by johbo** [comment]
Happy 2018! It's some time ago, but maybe mentioning NixCon? There is a nice wrap up in the holidaycheck blog here: http://techblog.holidaycheck.com/post/2017/10/31/nixcon2017

**Comment by garbas** [comment]
@domenkozar @svanderburg @johbo thank you. I have included your comments. They should be published soon as a preview -> http://weekly.nixos.org/preview/2018/01-phoenixes-burst-into-flame.html

**Comment by domenkozar** [comment]
We are hiring SRE with Nix/Haskell knowledge at IOHK: https://iohk.io/careers/#op-144226-devops-engineer

**Comment by zimbatm** [comment]
How about a tips&tricks:

master now has a `pkgs.mkShell { }` to use in your shell.nix. It works like a standard derivation but is less verbose to type, doesn't require a name attribute.

Before:
```nix
{ pkgs ? import <nixpkgs> {} }:
pkgs.stdenv.mkDerivation {
  name = "my-shell";
  buildInputs = with pkgs; [ bash ];
}
```

After:
```nix
{ pkgs ? import <nixpkgs> {} }:
pkgs.mkShell {
  buildInputs = with pkgs; [ bash ];
}
```

**Comment by garbas** [comment]
@zimbatm I'm -1 on tips & tricks section.

While I was (and still am) tempted to add more *real* content to newsletter I always stop myself and remind myself that newsletter (at least currently) is a list of links. Collecting links and verifying that they point to correct location is one thing, collecting content and verifying it works is another thing, which I don't think I will have time to do.

That said I think ``mkShell`` should (actually must) be mentioned in the newsletter, but with a link to PR where there is an example and more detailed explanation.

Does this make sense?

I will add the following bullet point to Tooling section

- [mkShell](https://github.com/NixOS/nixpkgs/pull/30975) - for nix-shell-only scenarios, ``mkShell`` is a small convenience function in nixpkgs.

**Comment by zimbatm** [comment]
sure, no problem at all

**Comment by johbo** [comment]
might be an option to put the mkShell example somewhere into a blog and add a link to the bullet point, then we get best of both and interested people can follow.

**Comment by johbo** [comment]
haha, forget my comment, just saw it in the preview 👍

**Pull request merged**
