### PR TITLE
Call for Content: 2021/02

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by domenkozar** [comment]
- [Offloading NixOS builds to a faster machine](https://sgt.hootr.club/molten-matter/nix-distributed-builds/)
- [Build your NixOS Raspberry Pi Image using Github Action](https://github.com/lucernae/nixos-pi/)
- https://sandervanderburg.blogspot.com/2021/02/developing-s6-rc-backend-for-nix.html
- https://discourse.nixos.org/t/devops-service-reliability-engineer-nix-nixops-flakes-hydra/11353
- https://discourse.nixos.org/t/recurring-funding-for-making-macos-first-class-citizen-in-nix-ecosystem/11386

**Comment by Mic92** [comment]
```
- [envfs](https://github.com/Mic92/envfs)
  Fuse filesystem that returns symlinks to executables based on the PATH of the requesting process (fixes shebang problems on NixOS)
```

**Comment by SuperSandro2000** [comment]
```
- [nixpkgs-review-checks](https://github.com/SuperSandro2000/nixpkgs-review-checks)
  Add additional checks and more information from build logs and outputs to the reports generated by nixpkgs-review. 
```

**Comment by Ma27** [comment]
```
- [Safe service upgrades using system.stateVersion](https://nixos.mayflower.consulting/blog/2021/01/28/nextcloud-stateversion/)
```

**Comment by bpiv400** [comment]
```
- [Introducing flox - Nix for simplicity and scale](https://discourse.nixos.org/t/introducing-flox-nix-for-simplicity-and-scale/11275)
[flox](https://floxdev.com) makes it easy to build software or manage development environments with Nix at any scale
```

**Comment by adisbladis** [comment]
```
- [Trustix](https://www.tweag.io/blog/2020-12-16-trustix-announcement/)
  Trustix: Distributed trust and reproducibility tracking for binary caches
```

**Comment by Mic92** [comment]
```
- [Podcasts about Nix](https://www.compositional.fm/hosts/rok)
  A content addressable store for Nix with Théophane Hufschmitt and Binary Verification with Trustix starring Adam Höse
```

**Comment by gbpdt** [comment]
``` - [PDT Partners is looking for an experienced engineer](https://boards.greenhouse.io/pdtpartners/jobs/1473543) for our Software Infrastructure team, which is responsible for our build, packaging, CI and deployment tooling. We’re using Nix to package our complex C++ and Python stack, and as part of our wider development environment for our fast-moving trading and research applications.```

**Pull request merged**
