### PR TITLE
Call for Content: 2018/14

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch or a comment below. Thank you <3

### CODE REVIEW

**Comment by Ekleog** [comment]
```markdown
- [RFC0036 (Improving the RFC process) entered its Final Comments Period with a disposition of merge](https://github.com/NixOS/rfcs/pull/36)

  FCP will end on Dec. 20, so go and check no important point has been left undiscussed!
```

**Comment by domenkozar** [comment]
```
- [Hercules CI development update](https://blog.hercules-ci.com/hercules-ci/2018/12/18/hercules-ci-development-update/)

  A short demo of CI development progress in the last couple of weeks including what have we worked on.
```

**Comment by Synthetica9** [comment]
```markdown
- [Nix-linter v0.2.0.0 released](https://github.com/Synthetica9/nix-linter/releases)

Nix-linter is a program to check for several common mistakes or stylistic errors in Nix expressions, such as unused arguments, empty let blocks, etcetera. 
```

**Comment by domenkozar** [comment]
```
- [Nix community attended Reproducible builds summit](https://discourse.nixos.org/t/reproducible-builds-summit-report/1683/2)
```

**Comment by domenkozar** [comment]
job: https://www.reddit.com/r/NixOS/comments/a5hvjw/devops_team_lead_nixnixops/

**Pull request merged**
