### PR TITLE
Call for Content: 2018/10

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```rst
- Example news item title `with link`_

  News item description in one or two sentences.

.. _`with link`: http://example.com
```

preferably as a PR against `master` branch or a comment below. Thank you <3

### CODE REVIEW

**Comment by domenkozar** [comment]
Add developer friendly backdoor to VM tests infrastructure: https://github.com/NixOS/nixpkgs/pull/47418

**Comment by domenkozar** [comment]
http://hackage.haskell.org/package/cachix-0.1.2/changelog

**Comment by domenkozar** [comment]
https://twitter.com/IotaSamurai/status/1045220406792048640

**Comment by domenkozar** [comment]
https://functional.works-hub.com/learn/exploring-nix-and-haskell-part-1-project-setup-0edb2?utm_source=twitter&utm_medium=post&utm_campaign=kenny

**Comment by domenkozar** [comment]
https://discourse.nixos.org/t/new-aarch64-and-armv7l-linux-omg-builders/1010

**Comment by mogorman** [comment]
New shirt and logo for 18.09 release https://www.redbubble.com/people/mogorman/works/34062374-nixos-18-09-jellyfish?asc=u

**Comment by mrVanDalo** [comment]
```
- `krops as an alternative to NixOps`_

  NixOps the official DevOps tool of NixOS is nice, but it has some flaws. krops is an alternative to NixOps trying to solve some of theses flaws.

.. _`krops as an alternative to NixOps`: https://tech.ingolf-wagner.de/nixos/krops/
```

**Comment by domenkozar** [comment]
https://snowflake.semilattice.org/intro.html

**Comment by Mic92** [comment]
@domenkozar the certificate of the last link is broken.

**Comment by Profpatsch** [comment]
@domenkozar I think we already listed snowflake before, so the announcement of `0.0.2` might be more interesting: https://groups.google.com/forum/#!topic/snowflake-announcements/4t4JXbYZP3k

**Comment by grahamc** [comment]
Optimising Docker Layers for Better Caching with Nix https://grahamc.com/blog/nix-and-layered-docker-images

Check out how Graham created Nix tooling to automatically build Docker images with great cache characteristics by using Nix's reference graph to separate out important layers.

**Comment by Ekleog** [comment]
Found on Discourse:
```
- `Japanese on NixOS`_

  An explanation of how to setup an environment for reading and writing Japanese on NixOS

.. _`Japanese on NixOS`: https://functor.tokyo/blog/2018-10-01-japanese-on-nixos
```

**Comment by domenkozar** [comment]
Thank you all, I'm crafting the weekly now - this one is packed!

**Pull request merged**
