### PR TITLE
Call for Content: 2019/06

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by marsam** [comment]
- [NIXML: nix + YAML for easy reproducible environments](https://metarabbit.wordpress.com/2019/03/12/nixml-nix-yaml-for-easy-reproducible-environments/)

**Comment by kalbasit** [comment]
- [Announcing the new Golang infrastructure: buildGoModule](https://kalbas.it/2019/03/17/announcing-the-new-golang-infrastructure-buildgomodule/)

**Comment by domenkozar** [comment]
Thanks! Moving to next week due to low volume :)

**Comment by 4z3** [comment]
- [_Why Use NixOS_ wiki page is looking for authors](https://nixos.wiki/wiki/Why_Use_NixOS)

At the moment it's an empty page, but maybe it's worth putting it into weekly to reach some inclined people to add their arguments. :)

**Comment by domenkozar** [comment]
@4z3 I'd prefer not to do that as it will yield wiki wars. Best to advertise on discourse if you'd like dev's attention.

**Comment by kalbasit** [comment]
- [Why I use NixOS](https://kalbas.it/2019/03/24/why-i-use-nixos/)

Hopefully, no blog wars :rofl:

**Comment by domenkozar** [comment]
- [Announcing tree sitter nix](https://discourse.nixos.org/t/announcing-tree-sitter-nix/2483)

- [Announcing Mixnix - Build Elixir projects with Nix](https://discourse.nixos.org/t/announcing-mixnix-build-elixir-projects-with-nix/2444)

**Comment by domenkozar** [comment]
This weekly will be one day late.

**Comment by grahamc** [comment]
Target and Tweag announce lorri, a nix-shell replacement for project development. lorri is based around fast direnv integration for robust CLI and editor integration.

Read about it at https://www.tweag.io/posts/2019-03-28-introducing-lorri.html and try it out at http://github.com/target/lorri!

**Comment by domenkozar** [comment]
https://nixos.org/releases/patchelf/patchelf-0.10/

**Comment by domenkozar** [comment]
https://github.com/justinwoo/format-nix

**Comment by domenkozar** [comment]
Sorry y'all, last week was hectic so I'll ship this one on 3rd of April. Pinky swear :)

**Comment by gotcha** [comment]
> Sorry y'all, last week was hectic so I'll ship this one on 3rd of April. Pinky swear :)

This is today ;-)

**Comment by domenkozar** [comment]
Working on it as you speak :)

**Pull request merged**
