### PR TITLE
Call for Content: 2019/04

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch or comment below. Thank you <3

### CODE REVIEW

**Comment by zimbatm** [comment]
```
- [Deploying Kubernetes apps with KubeNix](https://zimbatm.com/deploying-k8s-apps-with-kubenix/)
```

**Comment by domenkozar** [comment]
@zimbatm already featured in https://weekly.nixos.org/2019/03-kubenix-kernel-regressions-and-jobs.html

**Comment by softinio** [comment]
- [Moving from Homebrew to Nix Package Manager](https://www.softinio.com/post/moving-from-homebrew-to-nix-package-manager/)

**Comment by domenkozar** [comment]
That one was also in last issue :)

**Comment by domenkozar** [comment]
- [Static Nix: a command-line swiss army knife](https://matthewbauer.us/blog/static-nix.html)

**Comment by kalbasit** [comment]
- [Nix SRE position in San Francisco, CA](https://jobs.lever.co/keeptruckin/464c5b6a-ccad-467e-a7c6-c96ec6cb4ce0).
- [Manage a static website with Hugo and Nix](https://kalbas.it/2019/02/26/manage-a-static-website-with-hugo-and-nix/)

**Comment by domenkozar** [comment]
Thanks all!

**Pull request merged**
