### PR TITLE
fixes for travis

### PR DESCRIPTION
**Pull request by badmutex**
I ran into travis issues related to nix 2.0 release in the travis build for issue 2018/03 (#50) .
See for example https://travis-ci.org/NixOS/nixos-weekly/builds/345812512.

Once the changes work on this branch I'll merge to master.

### CODE REVIEW

**Comment by badmutex** [comment]
[Current error](https://travis-ci.org/NixOS/nixos-weekly/builds/345822268#L479) is
```
error: store path mismatch in file downloaded from 'https://github.com/NixOS/nixpkgs-channels/archive/ade98dc442ea78e9783d5e26954e64ec4a1b2c94.tar.gz'
```

**Comment by badmutex** [comment]
I was able to build using the [nixos/nix](https://hub.docker.com/r/nixos/nix) docker image, so I _may_ switch to that just so that we can get the 2018/03 issue out.

**Comment by badmutex** [comment]
I'll plan to merge this into master a few hours from the timestamp of this comment.

**Comment by zimbatm** [comment]
as long as it works, it can be made better later

**Pull request merged**
