### PR TITLE
Issue 2018/03

### PR DESCRIPTION
**Pull request by badmutex**
I'm creating this so there's one place to submit topics for the next issue.
Editor is @badi

- Please comment with a topic

- Date: 26/02/2018

- [Click to Preview](http://weekly.nixos.org/preview)

### CODE REVIEW

**Comment by badmutex** [comment]
From #48: https://github.com/jwiegley/nix-update-el

**Comment by badmutex** [comment]
Deploying systems with circular dependencies using Disnix  http://sandervanderburg.blogspot.com/2018/02/deploying-systems-with-circular.html?m=1

**Comment by badmutex** [comment]
Nix 2 plugins support https://github.com/NixOS/nix/pull/1854

**Comment by badmutex** [comment]
Simple Hydra https://github.com/ElvishJerricco/simple-hydra

**Comment by badmutex** [comment]
Grokking Hydra https://github.com/gilligan/groking-hydra

**Comment by Profpatsch** [comment]
nixos.wiki workgroups: https://nixos.wiki/wiki/Workgroup

and container workgroup https://nixos.wiki/wiki/Workgroup:Container

**Comment by zimbatm** [comment]
Nix hasn't been accepted by GSoC because our proposals weren't built well enough. We will do better next year. If you want to work this summer on Nix instead of flipping burgers, please contact me with your project proposal.

**Comment by garbas** [comment]
Haskell developer experience in NixOS
http://www.kuznero.com/posts/nixos/haskell-devexp-in-nixos.html

**Comment by garbas** [comment]
XMonad and Taffybar on NixOS using Stack
https://functor.tokyo/blog/2018-02-16-setup-xmonad-on-nixos

**Comment by garbas** [comment]
https://twitter.com/SusanPotter/status/964915725700825088

**Comment by garbas** [comment]
Parity as a service on NixOS
https://blog.aira.life/parity-as-a-service-on-nixos-3c0236ffe0a7

**Comment by garbas** [comment]
https://twitter.com/shlevy/status/965019194759761920

**Comment by shlevy** [comment]
@garbas Note https://twitter.com/shlevy/status/965034245990371334 for people who aren't part of the org.

**Comment by garbas** [comment]
new job announcement  https://groups.google.com/forum/#!topic/nix-devel/YvaXKCAInZ0

**Comment by Ericson2314** [comment]
Musl? :) @dtzWill

**Comment by dtzWill** [comment]
If not this week, then next! Or should we mention RFC 23? :)

**Comment by svanderburg** [comment]
another cool job announcement: https://groups.google.com/forum/#!topic/nix-devel/o0iCtlVVZZ0

**Comment by badmutex** [comment]
Nix 2.0 released https://github.com/NixOS/nix/commit/eaa52c34b40aa2f899280e6aa99d5fa0a420ad3a
Release notes: https://nixos.org/nix/manual/#sec-relnotes

---
edit: add release notes

**Comment by badmutex** [comment]
~Sandboxed builds enabled by default on Linux https://github.com/NixOS/nix/commit/ddc58e789636e1b94149c342575d92583251fbf6~

---
edit: this was [reverted](https://github.com/NixOS/nixos-weekly/pull/50#issuecomment-367839299)

**Comment by badmutex** [comment]
Upcoming 18.03 release https://groups.google.com/forum/#!msg/nix-devel/9sps8NLdwIY/etmZL4J6AAAJ

**Comment by dtzWill** [comment]
Sandboxed builds commit was reverted shortly thereafter: https://github.com/NixOS/nix/commit/e8d53bfdc94eea142542de92ff0822eb283d293f

(reverting isn't news, but just want to make sure "sandbox builds on by default" isn't included in the weekly if it's not :+1:)

**Comment by garbas** [comment]
Patreon to support the #NixOS OfBorg infrastructure
https://twitter.com/grhmc/status/967531653387169792
https://www.patreon.com/ofborg

**Comment by garbas** [comment]
Install VirtualBox on NixOS
https://functor.tokyo/blog/2018-02-24-virtualbox-on-nixos#.WpDmHrsjv4Q.twitter

**Comment by garbas** [comment]
Job offer -> NixOS, Haskell, DevOps, thrilling projects with little bureaucracy. Sounds like something you're into? Come work with us. 
https://twitter.com/serokell/status/953924463275409408

**Comment by garbas** [comment]
Annoucing dhall-build - a Dhall interface to the Nix build system
https://twitter.com/acid2/status/966801068133961729

**Comment by badmutex** [comment]
@garbas I'm unable to merge to `production`. Mind doing a review?

**Comment by mogorman** [comment]
new script to update package in nixos automagically https://github.com/ryantm/nix-update

**Comment by svanderburg** [comment]
Disnix 0.8 released: http://nixos.org/disnix

**Review by garbas — APPROVED** [review]

**Comment by garbas** [comment]
@badi i think this was because i added (before you took over) myself as reviewer. i'm merging this and sending out newsletters in next 5min

**Comment by badmutex** [comment]
Sounds good :)

**Comment by zimbatm** [comment]
@svanderburg where is the changelog?

**Comment by svanderburg** [comment]
@zimbatm Here it is: https://raw.githubusercontent.com/svanderburg/disnix/master/NEWS

Additionally, Dysnomia (its companion tool) has been updated as well: https://github.com/svanderburg/dysnomia/blob/master/NEWS

**Comment by Profpatsch** [comment]
Awesome issue +1

**Pull request merged**
