### PR TITLE
Call for Content: 2022/01

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by domenkozar** [comment]
- [NixOS Home Manager for multi-user on NIX flake Installation and Configuration](https://mudrii.medium.com/nixos-home-manager-on-native-nix-flake-installation-and-configuration-22d018654f0c)
- [advanced shell packaging: resholve YADM's nixpkg](https://t-ravis.com/post/nix/advanced_shell_packaging_resholve_yadm/)

**Comment by oppiliappan** [comment]
```
- [Novice Nix: Flake Templates](https://peppe.rs/posts/novice_nix:_flake_templates/)
```

**Comment by cole-h** [comment]
```
- [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock/)

  A GitHub Action to keep your flake.lock up to date.
```

**Comment by domenkozar** [comment]
https://github.com/NerdyPepper/statix

**Comment by Mic92** [comment]
```
- [RFC Steering Committee Rotation 2020/21](https://discourse.nixos.org/t/rfc-steering-committee-rotation-2020-21/9365)

  The RFC steering committee is looking for new members.

```

**Comment by domenkozar** [comment]
https://discourse.nixos.org/t/how-nix-and-nixos-get-so-close-to-perfect/16010

**Comment by domenkozar** [comment]
https://blog.replit.com/nix-vs-docker

**Comment by sternenseemann** [comment]
```
- [Tvix: We are rewriting Nix](https://tvl.fyi/blog/rewriting-nix)
```

**Comment by Mic92** [comment]
```
- [NixOS assembly on rC3 2021](https://discourse.nixos.org/t/nixos-assembly-on-rc3-2021/16409)
  Call for participation
```

**Comment by domenkozar** [comment]
- [Nix 2.5 released](https://nixos.org/manual/nix/stable/release-notes/rl-2.5.html)
- [A collection of Amateur Radio software packaged for Nix](https://github.com/MatthewCroughan/hamnix)
- [Call for Participation for FOSDEM Infra Management DevRoom](https://cfp.cfgmgmtcamp.org/fosdem2022/cfp)
- [deadnix](https://github.com/astro/deadnix)
  Finds and removes unused code in .nix files.
- [Configurable Nix packages](https://hoverbear.org/blog/configurable-nix-packages/)

**Comment by cab404** [comment]
```
 - [Nixovalnya: a Nix hackathon/lecture/party in Moscow & Online, March 5th](https://discourse.nixos.org/t/5th-march-nixovalnya-a-nix-hackathon-lecture-party-in-moscow-online/17791)
Call for lectures/participation
```

**Comment by aszlig** [comment]
```markdown
 - [NixOS on LINUX Unplugged](https://linuxunplugged.com/451)
```
~~URL doesn't work yet, since the show is not yet available, but it will be within the next few hours.~~

**Comment by domenkozar** [comment]
- https://linuxunplugged.com/451

**Comment by domenkozar** [comment]
- https://www.youtube.com/watch?v=qZyGSSkQlwU
- [Summer of Nix 2022](https://discourse.nixos.org/t/summer-of-nix-2022/18479)
- https://apply.workable.com/mlabs/j/89AB69AD61/
- https://discourse.nixos.org/t/build-engineer-intuitive-surgical-nix-bazel/18506
- https://christine.website/blog/nix-flakes-3-2022-04-07

**Pull request closed without merging**
