### PR TITLE
Call for Content: 2020/03

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by endgame** [comment]
```markdown
 - [nix-freeze-tree](http://jackkelly.name/blog/archives/2020/01/25/nix-freeze-tree/index.html)

   `nix-freeze-tree` is a utility that walks a directory tree, and writes out Nix expressions which rebuild that tree. The generated expressions have two important properties:
    1. Each file in the tree is built by a separate fixed-output derivation, and
    2. Directories are built by derivations that symlink their contents recursively.
    If you are using `nix copy` to ship a derivation between nix stores, copying the derivation built by evaluating the output of `nix-freeze-tree` can reuse existing files in the destination store, as fixed-output derivations can be checked against a hash before copying.
```

**Comment by domenkozar** [comment]
https://christine.website/blog/i-was-wrong-about-nix-2020-02-10

**Comment by danbst** [comment]
Nixpkgs reached 200,000 commits milestone. It took less than 3 years since [previous 100,000 milestone]( https://www.reddit.com/r/NixOS/comments/5rsqde/nixpkgs_just_hit_the_100000_commits_mark/)

**Comment by marsam** [comment]
```markdown
- [Nix for Coq Development](https://yannherklotz.com/blog/2020-02-15-nix-for-coq-development.html)
```

**Comment by luispedro** [comment]
```markdown
- [Possible nixpkgs-based Google Summer of Code projects](http://big-data-biology.org/positions/gsoc-tweag/). We want to try to use nix(pkgs) to build perfectly reproducible environments in a context where the users wouldn’t even be aware that nix is a thing that exists (unless, obviously, they want to know). This is in the context of a bioinformatics application, written in Haskell, but the nixpkgs integration can be done without writing Haskell code ([NGLess](https://ngless.embl.de/))
```

**Comment by domenkozar** [comment]
https://thomashartmann.dev/blog/nix-override-packages-with-overlays/

**Comment by domenkozar** [comment]
https://discourse.nixos.org/t/announcing-tuna-nix-mirror/6144

**Comment by domenkozar** [comment]
https://blog.hackeriet.no/oslo-nixos-minicon-rapport/

**Comment by domenkozar** [comment]
https://christine.website/blog/how-i-start-nix-2020-03-08

**Comment by danbst** [comment]
[Role-playing Nix: Being A Dragon-fighter](https://github.com/NixOS/nixpkgs/pull/82453)
Does everyone feel like a dragon-fighter sometimes?

**Comment by adisbladis** [comment]
How NixOS Is Enabling Edge and IoT Projects
https://www.worksonarm.com/blog/how-nixos-is-enabling-edge-and-iot-projects/

**Comment by Mic92** [comment]
Interactive tutorials for using Nix and Nixpkgs written as [Jupyter notebook](https://github.com/FRidh/nix-tutorials) made by [@FRidh](https://github.com/FRidh)

**Comment by domenkozar** [comment]
https://blog.cachix.org/post/2020-03-18-proposal-for-improving-nix-error-messages/

**Comment by svanderburg** [comment]
https://sandervanderburg.blogspot.com/2020/02/a-declarative-process-manager-agnostic.html

**Pull request merged**
