### PR TITLE
Call for Content: 2020/05

### PR DESCRIPTION
**Pull request by domenkozar**
Hi all,

please add Nix news item in form of:

```markdown
- [Example news item title](http://example.com)

  Optional item description.

```

preferably as a PR against `master` branch (or a comment below).

Thank you <3

### CODE REVIEW

**Comment by marsam** [comment]
```
- [My NixOS Desktop Flow](https://christine.website/blog/nixos-desktop-flow-2020-04-25)

- [Learn NixOS by turning a Raspberry Pi into a Wireless Router](https://hackmd.io/dnJSEwjSSHCkzWFSZwbxeA)

- [Installing NixOS on a Raspberry Pi 3](https://citizen428.net/blog/installing-nixos-raspberry-pi-3/)

- [Naive NixOS Rust Development](https://duan.ca/2020/05/07/nix-rust-development/)

- [nixology: nix screencasts by Burke Libbey](https://www.youtube.com/playlist?list=PLRGI9KQ3_HP_OFRG6R-p4iFgMSK1t5BHs)

- [NixOS on a Raspberry Pi: creating a custom SD image with OpenSSH out of the box](https://rbf.dev/blog/2020/05/custom-nixos-build-for-raspberry-pis/)

- [Keeping Up Appearances: Non-native macOS Light/Dark Mode](https://cmacr.ae/post/2020-05-03-keeping-up-appearances-non-native-macos-light-dark-mode/)

- [Super Bootable 64](https://christine.website/blog/super-bootable-64-2020-05-06)

- [Managing Firefox on macOS with Nix](https://cmacr.ae/post/2020-05-09-managing-firefox-on-macos-with-nix/)

- [Nix Generator Functions for Sway](https://cmacr.ae/post/2020-05-10-nix-generator-functions-for-sway/)

- [Functional Fika — Nix and Haskell](https://maxfieldchen.com/posts/2020-05-16-Functional-Fika-Haskell-Nix-Cabal.html)
```

**Comment by moaxcp** [comment]
[debugging the micronaut package and code smells in nix](https://dev.to/moaxcp/debugging-the-micronaut-package-and-code-smells-in-nix-dhh)

**Comment by ghost** [comment]
```markdown
- <a href="mumble://mumble.nix-community.org/?version=1.2.0">Nix Community Mumble</a>

  A Mumble sever has been provisioned for use by the Nix community. Feel free to lurk in the lobby or create your own channels for hosting meetings and discussions. Join with `nix run nixpkgs.mumble -c mumble mumble://$USER@mumble.nix-community.org`.
```

**Comment by domenkozar** [comment]
https://earnestcapital.com/earnest-capital-invests-in-cachix/

**Comment by kolloch** [comment]
What is the preferred way to add links to the newsletter? I will just do that but I need to know what it is.

I created a PR, as suggested at the beginning of this thread, to be told that "this thread" is how we add links. I assume as a comment :

```md

- [Nix: Re-running Fixed Output Derivations - At the Right Time](https://blog.eigenvalue.net/nix-rerunning-fixed-output-derivations/)

  Have you ever been burned by forgetting to update a hash of a Fixed Output
  Derivations? Or realizing it hasn't worked since a while during an update?

  This article explores your options at re-running fixed output derivations on
  input changes.
```

**Comment by domenkozar** [comment]
A PR is also fine, although I edit the post anyway so it's about the same amount of work for me :)

**Comment by lazamar** [comment]
- [Nix Package Versions](https://lazamar.co.uk/nix-versions)
A tool to find all past versions of a package that were available in a channel, the revision you can download it from, and a copy-paste command for how to install it.

**Comment by vlktomas** [comment]
```
- [nix-examples](https://github.com/vlktomas/nix-examples)

  Showcase of Nix usage for various technologies.
```

**Comment by domenkozar** [comment]
- https://github.com/johnae/nixkite

- https://engineering.shopify.com/blogs/engineering/what-is-nix

- https://www.tweag.io/posts/2020-05-25-flakes.html

**Comment by thmzlt** [comment]
https://thomazleite.com/posts/development-with-nix-python/

**Comment by svanderburg** [comment]
[Deploying heterogeneous service-oriented systems locally with Disnix](https://sandervanderburg.blogspot.com/2020/05/deploying-heterogeneous-service.html)

**Pull request merged**
